version: '3'
services:
  postgres:
    image: postgres:11.9
    restart: always
    ports:
      - 15432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data     
    environment:
      POSTGRES_USER: "prisma"
      POSTGRES_PASSWORD: "prisma"
      POSTGRES_DB: "sabdb"
